name = "sherlock"
defaultTargets = ["Sherlock", "sherlock"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.28.0"

[[lean_lib]]
name = "Sherlock"

[[lean_exe]]
name = "sherlock"
root = "SherlockMain"